# Generated by Django 2.2 on 2021-11-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StatusSenha',
            fields=[
                ('id_status_senha', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id_senha', models.AutoField(primary_key=True, serialize=False)),
                ('senha', models.IntegerField()),
                ('hora_data', models.DateTimeField()),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Categoria')),
                ('id_status_senha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.StatusSenha')),
                ('id_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Tipo')),
            ],
        ),
    ]
